### model
model_name_or_path: meta-llama/Meta-Llama-3-8B
trust_remote_code: true
cache_dir:

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: open_thoughts3
cutoff_len: 4096
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves-llama3-8b
logging_steps: 32
save_steps: 128
save_strategy: "steps"   # or "epoch"
save_total_limit: 1      # Limit number of checkpoints saved
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swe  anlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint:

## eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 16

modelopt:
  quant_cfg: NVFP4_DEFAULT_CFG
  calib_size: 1024
  compress: false
  distill: false
  teacher_model: meta-llama/Meta-Llama-3-8B
